listener:
  slotName: myslot_1
  refreshConnection: 30s
  heartbeatInterval: 10s
  filter:
    tables:
      seasons:
        - insert
        - update
  topicsMap:
    schema_table_name: "notifier"
logger:
  caller: false
  level: info
  format: json
database:
  host: localhost
  port: 5432
  name: my_db
  user: postgres
  password: postgres
  debug: false
nats:
  address: localhost:4222
  streamName: "wal_listener"
  topicPrefix: ""
pubsub:
  topic: pubsub_topic_name
monitoring:
  sentryDSN: ""
  promAddr: ":2112"
